categories:
- Next Gen Mappers
description: A Scalable GPU System for Pairwise Whole Genome Alignments based on LASTZ's seed-filter-extend paradigm.
homepage_url: https://github.com/gsneha26/SegAlign
long_description: |
  SegAlign is a scalable, GPU-accelerated system for computing pairwise
  WGA. SegAlign is based on the standard seed-filter-extend heuristic, 
  in which the filtering stage dominates the runtime.
name: segalign
owner: richard-burhans
remote_repository_url: https://github.com/richard-burhans/galaxytools/tree/main/tools/segalign
type: unrestricted
